# Generated by Django 3.2 on 2025-06-30 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(choices=[('Kiloan', 'Paket Kiloan'), ('Cuci Kering', 'Paket Cuci Kering'), ('Cuci Setrika', 'Paket Cuci Setrika')], max_length=100)),
                ('harga_per_kg', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('nama_pelanggan', models.CharField(max_length=100)),
                ('berat_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laundry_app.produk')),
            ],
        ),
    ]
