# Generated by Django 3.2 on 2025-06-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='nama',
            field=models.CharField(max_length=100),
        ),
    ]
